# detector args
det_model_name: "det_model.ncnn"
det_input_height: 640
det_input_width: 640
# det_cond_thre: 0.5
# det_nms_thre: 0.45
# det_equal_scale: true

# fpr classifier args
fpr_model_name: "fpr_model.ncnn"
fpr_input_height: 224
fpr_input_width: 224
# cls_equal_scale: false


# tracker args
iou_thresh: 0.2                      
active_thresh: 1.1
inactive_thresh: 0.8
finish_thresh: 0.4
det_weak_thresh: 0.2
det_display_thresh: 0.2              
display_shift_tolerance: 10          
filter_big_lesion: true              
max_patch_number_per_tracklet: 100
