/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Android_Infer */

#ifndef _Included_com_Android_Infer
#define _Included_com_Android_Infer
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_Android_Infer
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_Android_Infer_nativeCreate(JNIEnv *, jobject);

/*
 * Class:     com_Android_Infer
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_Android_Infer_nativeDestroy(JNIEnv *, jobject,
                                                            jlong);

/*
 * Class:     com_Android_Infer
 * Method:    initialize
 * Signature: (JLcom/Android/SDKConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_Android_Infer_initialize(JNIEnv *, jobject,
                                                         jlong, jobject);

/*
 * Class:     com_Android_Infer
 * Method:    pushInput
 * Signature: (JLcom/Android/InputPacket;)I
 */
JNIEXPORT jint JNICALL Java_com_Android_Infer_pushInput(JNIEnv *, jobject,
                                                        jlong, jobject);

/*
 * Class:     com_Android_Infer
 * Method:    terminate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_Android_Infer_terminate(JNIEnv *, jobject,
                                                        jlong);

/*
 * Class:     com_Android_Infer
 * Method:    tryGetNext
 * Signature: (J)Lcom/Android/OutputPacket;
 */
JNIEXPORT jobject JNICALL Java_com_Android_Infer_tryGetNext(JNIEnv *, jobject,
                                                            jlong);

/*
 * Class:     com_Android_Infer
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_Android_Infer_getVersion(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
