/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Android_Infer */

#ifndef _Included_com_Android_Infer
#define _Included_com_Android_Infer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Android_Infer
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ai_workflow_AIWorkflowSDK_create(JNIEnv *,
                                                                 jobject);

/*
 * Class:     com_Android_Infer
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ai_workflow_AIWorkflowSDK_nativeDestroy(JNIEnv *,
                                                                       jobject,
                                                                       jlong);

/*
 * Class:     com_Android_Infer
 * Method:    initialize
 * Signature: (Lcom/android/infer/SDKConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_ai_workflow_AIWorkflowSDK_initialize(JNIEnv *,
                                                                    jobject,
                                                                    jobject);

/*
 * Class:     com_Android_Infer
 * Method:    pushInput
 * Signature: (Lcom/android/infer/InputPacket;)I
 */
JNIEXPORT jint JNICALL Java_com_ai_workflow_AIWorkflowSDK_pushInput(JNIEnv *,
                                                                   jobject,
                                                                   jobject);

/*
 * Class:     com_Android_Infer
 * Method:    calcCurrentROI
 * Signature: (Lcom/android/infer/ImageData;Lcom/android/infer/Rect;)I
 */
JNIEXPORT jint JNICALL Java_com_ai_workflow_AIWorkflowSDK_calcCurrentROI(
    JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_Android_Infer
 * Method:    tryGetNextOutput
 * Signature: (Lcom/android/infer/OutputPacket;)I
 */
JNIEXPORT jint JNICALL
Java_com_ai_workflow_AIWorkflowSDK_tryGetNextOutput(JNIEnv *, jobject, jobject);

/*
 * Class:     com_Android_Infer
 * Method:    terminate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ai_workflow_AIWorkflowSDK_terminate(JNIEnv *,
                                                                   jobject);

/*
 * Class:     com_Android_Infer
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ai_workflow_AIWorkflowSDK_getVersion(JNIEnv *,
                                                                       jclass);

#ifdef __cplusplus
}
#endif
#endif
