/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ultrasound_UltraSound */

#ifndef _Included_com_ultrasound_UltraSound
#define _Included_com_ultrasound_UltraSound
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ultrasound_UltraSound
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ultrasound_UltraSound_nativeCreate(JNIEnv *,
                                                                    jobject);

/*
 * Class:     com_ultrasound_UltraSound
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ultrasound_UltraSound_nativeDestroy(JNIEnv *,
                                                                    jobject,
                                                                    jlong);

/*
 * Class:     com_ultrasound_UltraSound
 * Method:    initialize
 * Signature: (JLcom/ultrasound/SDKConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_ultrasound_UltraSound_initialize(JNIEnv *,
                                                                 jobject, jlong,
                                                                 jobject);

/*
 * Class:     com_ultrasound_UltraSound
 * Method:    pushInput
 * Signature: (JLcom/ultrasound/InputPacket;)I
 */
JNIEXPORT jint JNICALL Java_com_ultrasound_UltraSound_pushInput(JNIEnv *,
                                                                jobject, jlong,
                                                                jobject);

/*
 * Class:     com_ultrasound_UltraSound
 * Method:    terminate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ultrasound_UltraSound_terminate(JNIEnv *,
                                                                jobject, jlong);

/*
 * Class:     com_ultrasound_UltraSound
 * Method:    tryGetNext
 * Signature: (J)Lcom/ultrasound/OutputPacket;
 */
JNIEXPORT jobject JNICALL Java_com_ultrasound_UltraSound_tryGetNext(JNIEnv *,
                                                                    jobject,
                                                                    jlong);

/*
 * Class:     com_ultrasound_UltraSound
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ultrasound_UltraSound_getVersion(JNIEnv *,
                                                                    jobject);

#ifdef __cplusplus
}
#endif
#endif
